assemblyline_ui/static/js/ng-utils.js

https://cccs.atlassian.net/browse/AL-534

Added scrollable option to table if too big

---

assemblyline_ui/api/v4/service.py
assemblyline_ui/api/v4/signature.py
assemblyline_ui/static/js/ng-utils.js
test/test_service.py

Relates to [I believe a space in the source field of signature sources break the YARA updater](https://cccs.atlassian.net/browse/AL-737)
Checks the source name if source is added from signatures or service page.

Fill in the gaps

---

assemblyline_ui/api/v4/service.py

Previous code wouldn't allow removal of sources to occur

Split-up conditions

---

assemblyline_ui/api/v4/service.py

Reverts CybercentreCanada/assemblyline-ui#18

Revert "Split-up conditions"

---

assemblyline_ui/api/v4/user.py
assemblyline_ui/helper/user.py

This change does not affect APIs use in the current UI. They should only affect the futur UI

Instead of faking the TOS was agreed to, let's have a bool that tells us if there is one set.

---

assemblyline_ui/api/v4/user.py
assemblyline_ui/error.py
assemblyline_ui/helper/user.py

In this patch, the whoami api call will return a flag saying if tos_lockout_auto_notify is turned on. It will also return a configuration block with every api calls that result in a 401 so the new React UI knows what are the possible ways to login.
This should have no effect on the current UI.

React ui api changes

---

assemblyline_ui/api/v4/help.py
assemblyline_ui/api/v4/user.py

Should have no impact on current UI since it does not use this API.

Change the whoami API to return all the configuration parts

---

assemblyline_ui/static/ng-template/signature_source.html

Related to: [Signature sources: Add support for adding certificate...](https://cccs.atlassian.net/browse/AL-842)

CA cert and ignore ssl error flags to UI for signature sources

---

assemblyline_ui/api/v4/service.py

Patch for source management bug in services api.
If accessed delta[update_config][sources] once, might as well move code that will do it again just to be safe.

move code block under condition (context)

---

assemblyline_ui/api/v4/user.py
assemblyline_ui/helper/service.py
assemblyline_ui/helper/views.py
assemblyline_ui/templates/base.html
assemblyline_ui/views.py
test/docker-compose.yml

This patch adds user settings and page hooks to auto-redirect to the new UI if the user has opt-in to the new UI.

Allow the current UI to recognize and interact with the new UI

---

assemblyline_ui/static/ng-template/signature_source.html

Changes to the UI for [Add proxy support to signature updater](https://cccs.atlassian.net/browse/AL-939)
Changes to odm are in this PR: https://github.com/CybercentreCanada/assemblyline-base/pull/48

Add proxy support in signature updater

---

assemblyline_ui/static/js/admin_service_configs.js
assemblyline_ui/static/js/ng-utils.js
assemblyline_ui/static/ng-template/docker_config.html
assemblyline_ui/static/ng-template/docker_config_edit.html
assemblyline_ui/static/ng-template/service_config.html

This fix the process to add dependency containers to a service in the UI

Fix adding dependency containers to service management

---

assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py
assemblyline_ui/api/v4/ui.py
assemblyline_ui/config.py
assemblyline_ui/helper/submission.py

Add submission received event to submit/ingest api endpoints that create a submission.

Submission lifecycle pubsub events 

---

assemblyline_ui/api/v4/search.py

Simplify search params gathering code and make sure boolean arguments are reported as booleans.

Fix disabling search on archive

---

assemblyline_ui/api/v4/authentication.py
assemblyline_ui/views.py

Do not let oauth providers allow login without email addresses

Hotfix/oauth email 

---

docker/socketio/Dockerfile
docker/ui/Dockerfile
test/test_live.py
test/test_submit.py

Adjust tests due to changes in core

---

docker/socketio/Dockerfile
docker/ui/Dockerfile
test/test_live.py
test/test_submit.py

Revert "Adjust tests due to changes in core"

---

assemblyline_ui/config.py

Tests failing due to pipeline issue. Unrelated to changes made in this branch.

Enable auditing at the INFO level, don't follow log_level

---

assemblyline_ui/api/v4/live.py
test/test_live.py

Bring back tests for the new dispatcher's live messages

dispatcher-refactor

---

assemblyline_ui/api/v4/signature.py
test/test_signature.py

Related to: https://cccs.atlassian.net/browse/AL-1072

Validate private key in sig. sources

---

assemblyline_ui/api/v4/service.py

Forgot to add this to modify source management from the Services page.

allow changes from services page also to apply

---

assemblyline_ui/api/v4/service.py
assemblyline_ui/api/v4/signature.py
test/test_signature.py

PROD: Validate private key

---

assemblyline_ui/api/v4/signature.py

Details: https://github.com/CybercentreCanada/assemblyline-ui/pull/116
Test on staging now shows the # of disabled rules in AL matches the # of rules with deprecations in the repo.

PROD: Allow AL to disable signatures if they become deprecated

---

assemblyline_ui/api/v4/service.py
assemblyline_ui/api/v4/signature.py

Completed: https://github.com/CybercentreCanada/assemblyline-ui/pull/127
Test on staging successful.

PROD: Update all classification of signatures

---

assemblyline_ui/api/v4/authentication.py

Emergency fix for signup process

hotfix/signup (dev)

---

assemblyline_ui/api/v4/ui.py

Respond with proper http codes for missing or partial chunks

Hotfix/flowjs (dev)

---

assemblyline_ui/api/v4/ingest.py

Use proper flask files method and bail early on size error.

hotfix/ingest_file_size (dev)

---

sample/obo_app.py
sample/templates/index.html

Additional improvments to OBO Sample to make it easier to understand

hotfix/obo_sample (dev)

---

assemblyline_ui/api/v4/submit.py

Get submission time form original submission/file

hotfix/submission_client (dev)

---

docker/ui/Dockerfile

Reverts CybercentreCanada/assemblyline-ui#267

Revert "Normalize change to dockerfile between master and dev"

---

docker/socketio/Dockerfile
docker/ui/Dockerfile

An old branch made a change to the docker files that was never merged into master.

Normalize change to dockerfile between master and dev

---

assemblyline_ui/api/v4/authentication.py

Better exception handling of oAuth errors

---

assemblyline_ui/api/v4/service.py

Closes: https://cccs.atlassian.net/browse/AL-1498

Global Registry Type for Services

---

assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py

Related PR: https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/325

Guard analysis-by-hash against file classification tampering

---

assemblyline_ui/api/v4/service.py

WRT: CybercentreCanada/assemblyline-core#573

Move where service event is sent so recivers can load heuristics (dev)

---

assemblyline_ui/api/v4/service.py

WRT: CybercentreCanada/assemblyline-core#573

Move where service event is sent so recivers can load heuristics

---

assemblyline_ui/api/v4/submit.py

Depends on CybercentreCanada/assemblyline-core/pull/637

DTL enforcement (dev)

---

assemblyline_ui/api/v4/submit.py

depends on CybercentreCanada/assemblyline-core/pull/638

DTL Enforcement

---

assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py
assemblyline_ui/helper/submission.py

Fix url_redirect crash and list the url history

URL Redirect fix

---

assemblyline_ui/api/v4/service.py
assemblyline_ui/api/v4/signature.py

A call used by the UI/API to trigger the service updater about changes. No longer used because of changes to Source Management

Remove use of _reset_service_updates (not used)

---

assemblyline_ui/api/v4/user.py

Added the retrohunt configuration to the "whoami" response.

Retrohunt (dev): Changed the retrohunt configuration

---

assemblyline_ui/api/v4/federated_lookup.py
plugins/external_lookup/assemblyline_lookup/app.py
plugins/external_lookup/assemblyline_lookup/test_app.py
plugins/external_lookup/malware_bazaar/app.py
plugins/external_lookup/malware_bazaar/test_app.py
plugins/external_lookup/template/app.py
plugins/external_lookup/virustotal/app.py
plugins/external_lookup/virustotal/test_app.py
test/test_federated_lookup.py

Fix logic in determining tag classification.
Return errors in api response.

Feature/lookup external (Dev)

---

assemblyline_ui/api/v4/federated_lookup.py
assemblyline_ui/api/v4/user.py
plugins/external_lookup/virustotal/app.py
test/test_federated_lookup.py

update vt result link

---

assemblyline_ui/api/v4/help.py
assemblyline_ui/api/v4/service.py
assemblyline_ui/helper/service.py
assemblyline_ui/helper/user.py
test/test_submit.py
test/test_user.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/16

Add service filtering based on user classification

---

assemblyline_ui/api/v4/retrohunt.py

Using the new multiget_search to search for the retrohunt hits and added pagination to the errors.

Retrohunt (dev): Using multiget_search and error pagination

---

assemblyline_ui/api/v4/retrohunt.py

Added hits.query, hits.filters and access_control to hits search and added query and sorting to errors in Retrohunt.

Retrohunt (dev) : Added query, filters and access_control to the retrohunt hits response.

---

assemblyline_ui/api/v4/user.py

Added a function that parses the favorites to the right format and removes any duplicate favorite with the same name.

Favorites parsing (dev)

---

assemblyline_ui/api/v4/user.py
test/test_user.py

Added a function that parses the favorites to the right format and removes any duplicate favorite with the same name.

Favorites parsing

---

assemblyline_ui/helper/user.py
test/config/classification.yml
test/test_user.py

https://github.com/CybercentreCanada/assemblyline-base/pull/1337

Classification tests

---

plugins/external_lookup/virustotal/test_app.py

update vt tests to test correct output (master)

---

assemblyline_ui/api/v4/federated_lookup.py
assemblyline_ui/api/v4/file.py
assemblyline_ui/api/v4/hash_search.py
assemblyline_ui/api/v4/submission.py
assemblyline_ui/api/v4/user.py
plugins/external_lookup/assemblyline_lookup/app.py
plugins/external_lookup/assemblyline_lookup/test_app.py
plugins/external_lookup/malware_bazaar/app.py
plugins/external_lookup/malware_bazaar/test_app.py
plugins/external_lookup/template/app.py
plugins/external_lookup/virustotal/app.py
plugins/external_lookup/virustotal/test_app.py
test/config/classification.yml
test/test_federated_lookup.py

pull in data from external sources to display in frontend

Feature/add external enrichment (master)

---

assemblyline_ui/api/v4/file.py

Added the add, remove and get labels routes.

Malware Archive (dev)

---

assemblyline_ui/api/v4/badlist.py
assemblyline_ui/api/v4/replay.py
assemblyline_ui/api/v4/safelist.py
assemblyline_ui/api/v4/signature.py
assemblyline_ui/api/v4/user.py
assemblyline_ui/api/v4/workflow.py
assemblyline_ui/config.py

Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-1988

Update API to facilitate workflow syncing via Replay

---

assemblyline_ui/api/v4/submission.py

Filters the root file's result to generate the promoted section

Feature/Submission promoted sections (dev)

---

assemblyline_ui/helper/search.py

Changed the retrohunt's default sort field.

Retrohunt (dev)

---

assemblyline_ui/api/v4/alert.py

Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2975

Update APIs to support removing labels from alerts

---

assemblyline_ui/api/v4/service.py

Reverts CybercentreCanada/assemblyline-ui#655

Revert feature (Windows support)

---

assemblyline_ui/api/v4/hash_search.py
test/test_hash_search.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/164

Normalize input given to `hash_search` API

---

assemblyline_ui/api/v4/ingest.py
test/test_ingest.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/184

Allow paging of messages from notification queues

---

assemblyline_ui/api/v4/file.py

Added a check for ascii and strings routes to make sure the file_obj exists instead of just sending a crash response.

Hotfix/File Viewer (dev) 

---

assemblyline_ui/api/v4/file.py

Added a check for ascii and strings routes to make sure the file_obj exists instead of just sending a crash response.

Hotfix/File Viewer (master)

---

assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py
assemblyline_ui/api/v4/user.py
assemblyline_ui/helper/submission.py
plugins/external_filesource/simple_url/Dockerfile
plugins/external_filesource/simple_url/app.py
plugins/external_filesource/simple_url/gunicorn_config.py
plugins/external_filesource/simple_url/requirements.txt
plugins/external_filesource/simple_url/requirements_test.txt
test/test_ingest.py
test/test_submit.py

Related to:
- https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2909
- https://github.com/CybercentreCanada/assemblyline/issues/111
- https://github.com/CybercentreCanada/assemblyline/issues/168

Modify APIs to support fetching files by more than SHA256 hash

---

assemblyline_ui/api/v4/submission.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/215

Correct typo for promoting overall tag verdict to malicious

---

assemblyline_ui/api/v4/archive.py
assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py
assemblyline_ui/api/v4/ui.py
assemblyline_ui/api/v4/user.py
assemblyline_ui/config.py
assemblyline_ui/helper/service.py

Related to: 
- https://github.com/CybercentreCanada/assemblyline/issues/211
- https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3081

Metadata enforcement

---

assemblyline_ui/api/v4/authentication.py

Allow for unspecified NameId defined by settings attribute

saml username ignored username_attribute

---

assemblyline_ui/api/v4/authentication.py

Hotfix Auth (dev)

---

assemblyline_ui/api/v4/authentication.py
assemblyline_ui/api/v4/ingest.py

Cleanup oAuth autentication and added support to authenticate a token using the client secret

Hotfix Auth

---

assemblyline_ui/api/v4/file.py

Added a check for if there's no vector tags.

Bugfix/Similar Files (dev)

---

assemblyline_ui/api/v4/authentication.py
assemblyline_ui/config.py

Allow users to auth with WorkloadIdentityCredential

Added support for using WorkloadIdentity Auth

---

assemblyline_ui/api/v4/authentication.py

DefaultAzureCredential provides better flexibility and less configuration required.

Replaced WorkloadIdentityCredential with DefaultAzureCredential

---

assemblyline_ui/app.py

Updated AAD auth validator

---

assemblyline_ui/api/v4/system.py
assemblyline_ui/config.py

Dynamic Metadata Suggestions

---

assemblyline_ui/api/v4/badlist.py
test/test_badlist.py
test/test_safelist.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/259

Expand hash check existence to fuzzy hashes

---

assemblyline_ui/api/v4/workflow.py

Changed the set_workflow_status() data block to have a json format.

Bugfix/WorkflowDetail (master)

---

assemblyline_ui/api/v4/authentication.py

Reverts CybercentreCanada/assemblyline-ui#1014

Revert "Normalising token to match authlib token structure"

---

assemblyline_ui/api/v4/authentication.py

Reverts CybercentreCanada/assemblyline-ui#1013

Revert "Using full token."

---

assemblyline_ui/api/v4/authentication.py

Reverts CybercentreCanada/assemblyline-ui#1010

Revert "Manually setting token"

---

assemblyline_ui/api/v4/authentication.py

Reverts CybercentreCanada/assemblyline-ui#1008

Revert "Added FIC support - AAD"

---

assemblyline_ui/api/v4/authentication.py

Reverts CybercentreCanada/assemblyline-ui#1007

Revert "Fixed if statement"

---

assemblyline_ui/api/v4/authentication.py
assemblyline_ui/app.py

Reverts CybercentreCanada/assemblyline-ui#1006

Revert "Federated Identity Credentials"

---

assemblyline_ui/api/v4/help.py
assemblyline_ui/api/v4/user.py
assemblyline_ui/app.py
assemblyline_ui/config.py
assemblyline_ui/helper/user.py
test/test_user.py

add default zip password to UI. Add default zip password to be configured in default user settings. This is to address https://github.com/CybercentreCanada/assemblyline/issues/274

Add default zip password configuration in UI

---

assemblyline_ui/api/base.py
assemblyline_ui/api/v4/authentication.py
assemblyline_ui/config.py

Use audit logger for login success and failure when the audit_login flag is set

Audit Login (dev)

---

assemblyline_ui/api/v4/user.py

Append the public properties to the APIProxies dict

Update/Borealis (master)

---

assemblyline_ui/api/v4/service.py
assemblyline_ui/api/v4/signature.py
test/test_signature.py

Relates to:
- https://cccs.atlassian.net/browse/AL-3247
- https://github.com/CybercentreCanada/assemblyline/issues/136
- https://github.com/CybercentreCanada/assemblyline/issues/159
- https://github.com/CybercentreCanada/assemblyline/issues/248

Add API to toggle update source

---

assemblyline_ui/api/v4/proxy.py
assemblyline_ui/api/v4/workflow.py

Fixed the trailing slash in API routes.

Bugfix/TrailingSlash (master)

---

assemblyline_ui/api/v4/user.py
test/test_user.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/315

Handle cases where the value of `identity_id` was never assigned

---

assemblyline_ui/api/v4/ui.py

Moved the `description` before the update functions

Feature/SubmissionProfiles (dev)

---

assemblyline_ui/api/v4/submission.py

Add an event sender to notify the ingester when a submission has been (dev)

---

assemblyline_ui/api/v4/apikey.py
assemblyline_ui/helper/search.py

Changed the `add_apikey` response

Feature/APIKey (dev)

---

assemblyline_ui/api/v4/submission.py

Related to: https://github.com/CybercentreCanada/assemblyline/issues/335

Add an event sender to notify the ingester when a submission has been deleted

---

assemblyline_ui/security/saml_auth.py

Related to: https://discord.com/channels/908084610158714900/908717528082173983/1355157750648275078

Correct method to retrieving user roles using SAML

---

assemblyline_ui/api/v4/ingest.py
assemblyline_ui/api/v4/submit.py
pipelines/config.yml
setup.py
test/config/config.yml
test/docker-compose.yml
test/test_alert.py
test/test_submit.py

Related to: https://cccs.atlassian.net/browse/AL-3638

Fix: Inconsistent submission_profiles handling

---

assemblyline_ui/helper/submission.py

Deep copy the default settings before merging them with the submissions settings
Key point of https://github.com/CybercentreCanada/assemblyline/issues/346

Fix overwritting default settings

---

assemblyline_ui/api/v4/apikey.py

CybercentreCanada/assemblyline-base/pull/1951

Refresh on new key (dev)

---

assemblyline_ui/api/v4/apikey.py

CybercentreCanada/assemblyline-base/pull/1951

Refresh on new key

---

assemblyline_ui/api/v4/bundle.py

…e user requesting a bundle download

Update Bundle API to take into consideration the classification of th… (dev)

---

assemblyline_ui/api/v4/authentication.py
test/test_auth.py

Add an endpoint that is only accessible to the administrator to unset one time password (OTP) for other users.
https://cccs.atlassian.net/browse/AL-3615

add new endpoint for admin to unset_otp for other users

---

assemblyline_ui/api/v4/submit.py

Changed the `default_external_sources`

Hotfix/Submit (dev)

---

assemblyline_ui/api/v4/submit.py

Fixed an issue where the `ui_params` were improperly set

Hotfix/Submit (master)

---

assemblyline_ui/api/v4/file.py

Fixed the handling of when a file doesn't exists in the system

Hotfix/FileViewer (master)

---

assemblyline_ui/api/v4/authentication.py
assemblyline_ui/helper/submission.py

Allow external filesources to provide their own metadata to the submi… (dev)

---

assemblyline_ui/api/v4/user.py

Have API instruct to clients how to encode data when used with Extern… (dev)

---

assemblyline_ui/api/v4/user.py

Related to: [AL-3817](https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3817)

Have API instruct to clients how to encode data when used with ExternalLinks
