assemblyline_ui/static/css/default.css, assemblyline_ui/static/js/ng-utils.js
Added a horizontal scrollbar for the process tree result section component, usable whenever the process tree gets larger than the result section it's in.
https://cccs.atlassian.net/browse/AL-570
=> AL-570: Horizontal Scroll for Process Tree

assemblyline_ui/static/js/ng-utils.js
Process cards change colour based on the total signature score for a process.
Tooltip lists what signatures were hit. Should this include the score for each signature as well?
Could not figure out how to import glyphicons into ng-utils.
Directly related to https://github.com/CybercentreCanada/assemblyline-v4-service/pull/11
https://cccs.atlassian.net/browse/AL-466
=> Signatures are now relevant to processes

assemblyline_ui/api/base.py, assemblyline_ui/api/v4/service.py, assemblyline_ui/api/v4/signature.py, test/test_service.py
Relating to [Deleting source from "Services" doesn't work ](https://cccs.atlassian.net/browse/AL-716):
This change allows source management to be available from the Services menu which is what caused the Suricata issue we're seeing on prod (changes weren't being reflected properly). Same issue could occur with services relying on signature sources like YARA.
@cccs-douglass mentioned it's ill-advised to interrupt changes happening with the service_delta doc by making different changes concurrently; let one finish before you start another.
In this particular instance, I needed to grab what the service's current delta was before allowing it to save the new delta, otherwise I would lose information such as the original source list which is necessary for cleaning up sources that are to be …
=> Add/Remove signatures from Services

assemblyline_ui/static/js/search.js
Now for some reasons, Elasticsearch throws a "Rewrite first" error when targetted fields are not in the index. This will ignore the "Rewrite first" error messages when all buckets are queried at the same time.
=> Ignore Rewrite first errors when querying multiple bucket at the same time

assemblyline_ui/static/js/ng-utils.js
Added an if condition that is required if services submit a process dict that doesn't have the `signatures` key. It was causing an error in the UI in the present state.
=> Adding signature check

assemblyline_ui/error.py
In the new UI, we need access to some information about the current UI config when access is denied. This patch will output the minimal config info needed during a 403 page so the UI can correctly react.
=> Returns a configuration block when access is denied 

assemblyline_ui/api/base.py
This will allow us to turn XSRF checks back on for file download APIs.
=> Allow Cross-Site request forgery prevention tokens to be passed as the request param XSRF_TOKEN

assemblyline_ui/api/base.py, assemblyline_ui/api/v4/submit.py, assemblyline_ui/api/v4/ui.py, assemblyline_ui/error.py, assemblyline_ui/helper/user.py, assemblyline_ui/http_exceptions.py, test/test_submit.py
Letting flask catch an exception for us is always logged as an error.
A quota restriction isn't an error, to prevent it from being treated that way I've changed the places where we do quota checks to handle it with the same API response the exception would have created.
=> Quota without error

assemblyline_ui/api/v4/service.py
Without this every service update fails for stable systems
=> Emergency fix for udating stable services

assemblyline_ui/api/v4/result.py
The section hierarchy is missing from the multiples_keys API which is causing a less optimal rendering method. This will force the section_hierarchy to be generated.
=> The multiple_keys API should build the section_hierarchy

assemblyline_ui/api/v4/authentication.py, assemblyline_ui/app.py, assemblyline_ui/helper/oauth.py, assemblyline_ui/views.py
Allow oauth provider to use a client_credential type grant to query user and groups APIs. This allows Azure B2C user to be able to login using a B2C oauth tenant URI.
=> Add support for Azure AD B2C

assemblyline_ui/config.py
Tested and working on Rancher deployment; only audit logs are visible at the INFO level, other logs are visible at the defined logging level in the config. https://cccs.atlassian.net/browse/AL-1052
log_level=WARNING:
=> PROD: Enable auditing at the INFO level, don't follow log_level

assemblyline_ui/api/v4/signature.py
Relating to: https://cccs.atlassian.net/browse/AL-792
TL;DR: AL is doing the right thing by disabling signatures that are deprecated when they're first added. However, if a rule becomes deprecated after initial deployment, AL retains it's original state which isn't desirable (at least in the case for YARA).
This will allow AL to place the rule in a disabled state, which can be removed later on.
=> Allow AL to disable signatures when they've become deprecated

assemblyline_ui/api/v4/service.py, assemblyline_ui/api/v4/signature.py
Relating to: https://cccs.atlassian.net/browse/AL-1089 (1)
_"Changing the signature source classification only applies to new rules when it should apply to all in the ruleset"_
Changes made via the UI/API in regards to signature source classification will apply to all signatures already loaded into AL as well as any new ones (not just new ones only)
=> DEV: Update all classification of signatures

assemblyline_ui/gunicorn_config.py
Restart workers after 1000 requests to limit memory creeping
=> hotfix/gunicorn_workers (dev)

assemblyline_ui/api/v4/signature.py
=> Allow deleteing of invalid source and block furthur invalid source

assemblyline_ui/api/v4/service.py
Covers the case if users add a service manifest that doesn't contain $SERVICE_TAG for dynamic image assignment
=> Change conditions for applying global configs

assemblyline_ui/api/v4/signature.py
Update check and messaging since we want to add sources to a service regardless of if they generate signatures or not.
=> Correct check/message for adding sources to services

assemblyline_ui/api/v4/federated_lookup.py, assemblyline_ui/api/v4/hash_search.py, plugins/external_lookup/assemblyline_lookup/app.py, plugins/external_lookup/assemblyline_lookup/test_app.py, plugins/external_lookup/malware_bazaar/app.py, plugins/external_lookup/malware_bazaar/test_app.py, plugins/external_lookup/template/app.py, plugins/external_lookup/virustotal/app.py, plugins/external_lookup/virustotal/test_app.py
wsgi servers including flask will automatically unquote the url before determining the route (and remove duplicate slashes). Enforce double url encoding to ensure full urls can be submitted to exteranl services.
=> ensure correct quoting of tags.

assemblyline_ui/security/ldap_auth.py
UI and LDAP auth part for https://github.com/CybercentreCanada/assemblyline-base/pull/1548
Our LDAP structure uses memberUid instead of member on LDAP group objects, so the member uid is stored instead of the member dn. Therefore we would like to see this supported by AssemblyLine.
Is there any other area besides assemblyline_ui that would need to updated?
=> Enable group lookups using uid instead of dn

assemblyline_ui/api/v4/ingest.py, assemblyline_ui/api/v4/submit.py, test/test_ingest.py, test/test_submit.py
This makes it possible (although still discouraged) to submit files within the JSON data block of the submission (low volume), but not ingestion (high volume) API.
We would like to see this supported to avoid the need of implementing an API gateway between AssemblyLine and our ticket system / SOAR. Unfortunately, depending on the use case it only supports sending out raw binary files (plaintext e-mails) or base64-encoded files (attachments) to arbitrary webservice APIs.
Would you consider supporting this use case and merging this PR? Thanks in advance!
=> Allow submission of files within JSON data block

assemblyline_ui/app.py
Add an environment variable AL_SESSION_COOKIE_SAMESITE to allow configure Flask to set the samesite attribute on the session cookie.
PR https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/94 allows this environment variable to be set via values.yaml.
For reference see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
=> Set samesite attribute on session cookie

assemblyline_ui/api/v4/signature.py, test/test_signature.py
Added the clear_status() method in the signature API to reset the control of the status over to the signature's source
=> Feature/SignatureStatus (master)

assemblyline_ui/api/v4/file.py
In the /file/result route, ensure the tags are unique with the right safelisted and minimum classification value
=> Bugfix/UniqueTags (master)

assemblyline_ui/api/v4/file.py, test/test_file.py
Changed the FileViewer's API route to return a truncated value when the file's size is bigger than the limit. Also, lowered the max file size from 10MB to 1MB to improve the frontend's performance.
=> Feature/FileSize (dev)

assemblyline_ui/api/v4/file.py, test/test_file.py
Changed the FileViewer's API route to return a truncated value when the file's size is bigger than the limit. Also, lowered the max file size from 10MB to 1MB to improve the frontend's performance.
=> Feature/FileSize (master)

assemblyline_ui/api/v4/signature.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/333
=> API should suggest an update_interval for sources based on global settings

assemblyline_ui/api/v4/submit.py
Getting the `default_external_sources` from the `ui_params` instead of the `data`
=> Hotfix/Submit (dev)

assemblyline_ui/helper/submission.py, test/test_submit.py
To fix this issue: https://cccs.atlassian.net/browse/AL-3866
When submitting a file using 
`client.ingest(sha256=[SHA256], params={'ignore_cache':True}, fname="./[FILENAME]")`
The resulting filename in AL does not start with `./` , as it gets stripped.
=> Modify init submission to use the original specified filename
